author:
  name: "Mike Rouse"
  avatar: "/assets/images/headshot.webp"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:m.rouse@outlook.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/m-rouse/"
    - label: "YouTube — Archive: Early Work & Tests"
      icon: "fab fa-youtube"
      url: "https://youtube.com/playlist?list=PLAG8UYfYgf6D8xPvmJwNE7BY3AKH4wZ76&si=U19k2Quzc6F_oElb"
    # - label: "GitHub"
    #   icon: "fab fa-github"
    #   url: "https://github.com/mike-rouse"
    # - label: "Steam"
    #   icon: "fab fa-steam"
    #   url: "https://store.steampowered.com/app/APP_ID"

title: "Mike Rouse — Unity/C# Gameplay Programmer"
description: "Gameplay & Systems • Unity Generalist • PC · Mobile · VR"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

url: "https://mike-rouse.github.io"
baseurl: "" 

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag

locale: en-GB

sass:
  style: compressed

atom_feed:
  hide: true

defaults:
  - scope:
      path: ""
    values:
      layout: single
